### ISSUE TITLE
Csgo Update 02/02/2023 broke the gamedata

### ISSUE THREAD

**Issue by freakexeuLow** [Wend4r/Scoreboard-Language#4]
Hey Wender, wanted to report something :)

**OS and Game used:**
OS: Linux
Game: CSGO

**Issue description:**
L 02/03/2023 - 20:48:56: [SM] Exception reported: Failed to get "GCSDK::CreateSharedObjectSubclass<CEconPersonaDataPublic>" address
L 02/03/2023 - 20:48:56: [SM] Blaming: scoreboard_language.smx
L 02/03/2023 - 20:48:56: [SM] Call stack trace:
L 02/03/2023 - 20:48:56: [SM]   [0] SetFailState
L 02/03/2023 - 20:48:56: [SM]   [1] Line 178, D:\SourcePawn\plugins\Scoreboard\Scoreboard Language\addons\sourcemod\scripting\scoreboard_language.sp::OnPluginStart
L 02/03/2023 - 20:48:56: [SM] Unable to load plugin "scoreboard_language.smx": Error detected in plugin startup (see error logs)
L 02/03/2023 - 20:49:08: Error log file session closed.

**Comment by domikuss** [comment]
Hi, problem has been fixed.
https://github.com/Wend4r/Scoreboard-Language/commit/58bdb0b00e56b27a225c9eb4462ec7d4d4e9e375
